CREATE TABLE IF NOT EXISTS aplicacion.elementos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    apellido text COLLATE pg_catalog."default" NOT NULL,
    observacion text COLLATE pg_catalog."default" NOT NULL,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT elementos_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS aplicacion.elementos
    OWNER to postgres;

REVOKE ALL ON TABLE aplicacion.elementos FROM usuario_app;

GRANT ALL ON TABLE aplicacion.elementos TO postgres;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE aplicacion.elementos TO usuario_app;